kind: Service
apiVersion: v1
metadata:
  name: a-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: a-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080