apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  minReadySeconds: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: b-service
  template:
    metadata:
      labels:
        app: b-service
    spec:
      containers:
      - name: b-service
        image: registry.hub.docker.com/rentalcarsalisdaircole/hackathon-istio:b
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        ports:
        - containerPort: 8080
